import Head from 'next/head'
import { Inter } from 'next/font/google'
import { ThemeProvider, createTheme } from '@mui/material/styles';
import Dashboard from '@/components/dashboard';

export default function Home() {

  const theme = createTheme({
    typography: {
      fontFamily: "Poppins, sans-serif",
    },
  });
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
      <ThemeProvider theme={theme}>
        <Dashboard/>
      </ThemeProvider>
     
    </>
  )
}
